### PR TITLE
Create crowdsec-bin-1.4.6.ebuild_

### PR DESCRIPTION
**Pull request by necrose99**
-bin template for ebuild using prebuilt debian/debs 

preferred Croudsec would tweak  Goreleaseer ,  ie new linux variants 
**crowsec-release-static-arm64**..... etc...
while they have amd64 as is .. 
dev-lang/GHC use binaries to least jumpstart it... 
future **USE="SRC binary"** 
if bin ... URL/S = , unpack and cp bins as if golang compiler is done else build src's and as is.. 

intended for gentoo on IoT or quite legacy hardware .low ram ..  ie https://github.com/GenPi64
6-36 hour grinds sux... on iot in some cases it can drag on 4 or less gigs of ram etc... 

ppl also tend to let security lag on home iot so better to have than not... 

SRC is preferred but ....  
while not yet vetted fully 

RDEPS added !net-analyzer/crowdsec soft blocker 

to net-analyzer/crowdsec can add !net-analyzer/crowdsec-bin

### CODE REVIEW

**Comment by ToeiRei** [comment]
Would you mind naming the ebuild correctly?

**Comment by ToeiRei** [comment]
No offense - but did you test your ebuilds?

**Comment by necrose99** [comment]
this is of draft quality sure ... cell  phone wont quit nagging . w/./o phone ringing 
  i've added the croudsec discord server  , havent had a few to open vmware to debug..

**Comment by ToeiRei** [comment]
I see. I'll write it myself then.

**Comment by necrose99** [comment]
https://github.com/Necrohol/crowdsec-overlay/blob/main/net-analyzer/crowdsec-bin/crowdsec-bin-1.4.6.ebuild_

already refactored it

**Comment by ToeiRei** [comment]
you still have the name wrong and anything. Please repoen this pull request once it's actually **tested** **and** **working**

**Pull request closed without merging**
